// pages/relics/index.jsx
import { ModalMenu } from "../../components/Modal";
import { RELICS } from "../../data/en-US/relics/relicList";
import { setPageTitle } from "../../components/Layout";
import Head from 'next/head';
import Ads from "../../components/Ads";

function Relics() {
    return (
        <>
            <Head>
                <title>{setPageTitle('Relics')}</title>
                <meta name="description" content="Information about all the Relics in Tower of Fantasy Global and Chinese versions." />
            </Head>

            <img className="bg-img" src={`/static/images/relics/alternatedestiny.webp`} alt="Alternate Destiny" />
            <header>
                <h1>Relics</h1>
                <p>
                    Relics (aka Gadgets) are tools that aid the player in exploration or combat.
                </p>
            </header>

            <Ads unit="lb1" />
            
            <section>
                <h2><span style={{color: "var(--color-tier-s)"}}>SSR</span> Relics</h2>
                <ModalMenu list={RELICS} filter="rarity" target="SSR" />
            </section>

            <Ads unit="lb3" />
            <Ads unit="mpu1" />

            <section>
                <h2><span style={{color: "var(--color-tier-a)"}}>SR</span> Relics</h2>
                <ModalMenu list={RELICS} filter="rarity" target="SR" />
            </section>

            <Ads unit="mpu3" />
        </>
    );
}

export default Relics;

// src/routes/relics/+page.svelte
<script>
    import Menu from "$lib/components/Menu.svelte";
    import MenuItem from "$lib/components/MenuItem.svelte";
    import Ad from "$lib/components/Ad.svelte";
    import SectionNavigation from "$lib/components/SectionNavigation.svelte";

    export let data;
    const relics = data.items;
</script>

<svelte:head>
    <title>Relics | Tower of Fantasy Index</title>
    <meta
        name="description"
        content="Relics (aka Gadgets) are tools that aid the player in exploration or combat."
    />
    <meta property="og:title" content="Relics" />
    <meta
        property="og:description"
        content="Relics (aka Gadgets) are tools that aid the player in exploration or combat."
    />
    <meta
        property="og:image"
        content={`/images/UI/Artifact/icon/${relics[0].imgSrc}.webp`}
    />
    <meta name="theme-color" content="#377dcb" />
</svelte:head>

<SectionNavigation links={["ssr", "sr"]} />

<h1>Relics</h1>
<p>
    Relics (aka Gadgets) are tools that aid the player in exploration or combat.
</p>

<Ad unit="lb1" />
<Ad unit="mobile_mpu1" />

<h2 id="ssr"><span style="color: var(--tier-s)">SSR</span> Relics</h2>
<Menu>
    {#each relics.filter((r) => r.rarity === "SSR") as relic}
        <MenuItem href={relic.path} chinaOnly={relic.chinaOnly}>
            <img
                src={`/images/UI/Artifact/icon/${relic.imgSrc}.webp`}
                alt={relic.name}
                width="128"
                height="128"
                loading="lazy"
            />
            <span class="menu-item-name">{relic.name}</span>
        </MenuItem>
    {/each}
</Menu>

<Ad unit="lb3" />
<Ad unit="mobile_mpu2" />

<h2 id="sr"><span style="color: var(--tier-a)">SR</span> Relics</h2>
<Menu>
    {#each relics.filter((r) => r.rarity === "SR") as relic}
        <MenuItem href={relic.path} chinaOnly={relic.chinaOnly}>
            <img
                src={`/images/UI/Artifact/icon/${relic.imgSrc}.webp`}
                alt={relic.name}
                width="128"
                height="128"
                loading="lazy"
            />
            <span class="menu-item-name">{relic.name}</span>
        </MenuItem>
    {/each}
</Menu>
