// pages/cosmetics/avatars/index.jsx
import { ModalMenu } from "../../../components/Modal";
import { AVATARS } from "../../../data/en-US/cosmetics/cosmetics";
import { setPageTitle } from "../../../components/Layout";
import Head from 'next/head';
import Ads from "../../../components/Ads";

function Avatars() {
    return (
        <>
            <Head>
                <title>{setPageTitle('Avatars')}</title>
                <meta name="description" content="List of all avatars and how to obtain them in Tower of Fantasy Global and Chinese versions." />
            </Head>

            <img className="bg-img" src="/static/images/bg-1.webp" alt="Background Image" />
            <header>
                <h1>Avatars</h1>
                <p>
                    Avatars are images you can use to customize your personal page when someone views your data, and they appear when you send chat messages. Simulacrum Avatars can be acquired by raising the Awakening points of a Simulacrum that you own to 200.
                </p>
            </header>

            <Ads unit="lb1" />

            <section>
                <h2>Avatar List</h2>
                <ModalMenu list={AVATARS} />
            </section>

            <Ads unit="lb3" />
            <Ads unit="mpu1" />
        </>
    );
}

export default Avatars;

// src/routes/cosmetics/avatars/+page.svelte
<script>
    import SvelteMarkdown from "svelte-markdown";
    import avatars from "$lib/data/cosmetics/avatars.json";
    import Ad from "$lib/components/Ad.svelte";
</script>

<svelte:head>
    <title>Avatars | Tower of Fantasy Index</title>
    <meta name="description" content="List of cosmetic avatars and how to get them.">
    <meta property="og:title" content="Avatars" />
    <meta
        property="og:description"
        content="List of cosmetic avatars and how to get them."
    />
    <meta
        property="og:image"
        content={`/images/Icon/Avatar/${avatars[0].imgSrc}.png`}
    />
    <meta name="theme-color" content="#377dcb" />
</svelte:head>

<h1>Avatars</h1>
<p>
    Avatars shown on the <a href="/simulacra">Simulacra</a> page can be obtained
    by raising the respective simulacrum's Awakening points (friendship) to 200.
</p>

<Ad unit="lb1" />
<Ad unit="mobile_mpu1" />

<div class="table-wrapper">
    <table class="bg-alternate">
        <thead>
            <th>Item</th>
            <th>Source</th>
        </thead>
        <tbody>
            {#each avatars as avatar}
                <tr>
                    <td>
                        <div class="img-and-name">
                            <img
                                src={`/images/Icon/Avatar/${avatar.imgSrc}.png`}
                                alt={avatar.name}
                                width="128"
                                height="128"
                            />
                            <h2>{avatar.name}</h2>
                        </div>
                    </td>
                    <td>
                        <SvelteMarkdown source={avatar.source} />
                    </td>
                </tr>
            {/each}
        </tbody>
    </table>
</div>
