// src/routes/relics/+page.svelte
<script>
    import Menu from "$lib/components/Menu.svelte";
    import MenuItem from "$lib/components/MenuItem.svelte";

    export let data;
    const relics = data.items;
</script>

<h1>Relics</h1>
<p>
    Relics (aka Gadgets) are tools that aid the player in exploration or combat.
</p>

<h2><span style="color: var(--tier-s)">SSR</span> Relics</h2>
<Menu>
    {#each relics.filter((r) => r.rarity === "SSR") as relic}
        <MenuItem href={relic.path} chinaOnly={relic.chinaOnly}>
            <img
                src={`/images/UI/Artifact/icon/${relic.imgSrc}.png`}
                alt={relic.name}
                width="128"
                height="128"
            />
            <span>{relic.name}</span>
        </MenuItem>
    {/each}
</Menu>

<h2><span style="color: var(--tier-a)">SR</span> Relics</h2>
<Menu>
    {#each relics.filter((r) => r.rarity === "SR") as relic}
        <MenuItem href={relic.path} chinaOnly={relic.chinaOnly}>
            <img
                src={`/images/UI/Artifact/icon/${relic.imgSrc}.png`}
                alt={relic.name}
                width="128"
                height="128"
            />
            <span>{relic.name}</span>
        </MenuItem>
    {/each}
</Menu>

// src/routes/relics.tsx
import { ModalMenu } from "../components/Modal/Modal";
import { RELICS } from "../data/en-US/relics/relicList";
import { removeSpace } from "../utils/stringHelper";


function Relics() {
    const bgImg = "Alternate Destiny";
    return (
        <>
            <img className="bg-img" src={`/images/relics/${removeSpace(bgImg)}.png`} alt={bgImg} />
            <header>
                <h1>Relics</h1>
                <p>
                    Relics (aka Gadgets) are tools that aid the player in exploration or combat.
                </p>
            </header>
            
            <section>
                <h2><span style={{color: "var(--color-tier-s)"}}>SSR</span> Relics</h2>
                <ModalMenu type="relics" listContent={RELICS.filter(relic => relic.rarity === "SSR")} />
            </section>

            <section>
                <h2><span style={{color: "var(--color-tier-a)"}}>SR</span> Relics</h2>
                <ModalMenu type="relics" listContent={RELICS.filter(relic => relic.rarity === "SR")} />
            </section>

        </>
    );
}

export default Relics;
