// src/routes/matrices/+page.svelte
<script>
    import Menu from "$lib/components/Menu.svelte";
    import MenuItem from "$lib/components/MenuItem.svelte";

    export let data;
    const matrices = data.items;
</script>

<h1>Matrices</h1>
<p>
    Matrices (aka Chips) are items that can be attached to one of the four
    weapon slots (Emotion, Mind, Belief, and Memory) to provide stat boosts and
    special effects.
</p>
<p>
    Set effects will only be active when using the weapon that the matrices are
    attached to unless otherwise specified. Matrices can be strengthened similar
    to weapons, with each star unlocking higher values for the set effect.
</p>

<h2><span style="color: var(--tier-s)">SSR</span> Matrices</h2>
<Menu>
    {#each matrices.filter((m) => m.rarity === "SSR") as matrix}
        <MenuItem href={matrix.path} chinaOnly={matrix.chinaOnly}>
            <img
                src={`/images/Icon/yizhi/256/${matrix.imgSrc}.png`}
                alt={matrix.name}
                width="128"
                height="128"
            />
            <span>{matrix.name}</span>
        </MenuItem>
    {/each}
</Menu>

<h2><span style="color: var(--tier-a)">SR</span> Matrices</h2>
<Menu>
    {#each matrices.filter((m) => m.rarity === "SR") as matrix}
        <MenuItem href={matrix.path} chinaOnly={matrix.chinaOnly}>
            <img
                src={`/images/Icon/yizhi/256/${matrix.imgSrc}.png`}
                alt={matrix.name}
                width="128"
                height="128"
            />
            <span>{matrix.name}</span>
        </MenuItem>
    {/each}
</Menu>

<h2><span style="color: var(--tier-b)">R</span> Matrices</h2>
<Menu>
    {#each matrices.filter((m) => m.rarity === "R") as matrix}
        <MenuItem href={matrix.path} chinaOnly={matrix.chinaOnly}>
            <img
                src={`/images/Icon/yizhi/256/${matrix.imgSrc}.png`}
                alt={matrix.name}
                width="128"
                height="128"
            />
            <span>{matrix.name}</span>
        </MenuItem>
    {/each}
</Menu>

<h2><span style="color: var(--tier-c)">N</span> Matrices</h2>
<Menu>
    {#each matrices.filter((m) => m.rarity === "N") as matrix}
        <MenuItem href={matrix.path} chinaOnly={matrix.chinaOnly}>
            <img
                src={`/images/Icon/yizhi/256/${matrix.imgSrc}.png`}
                alt={matrix.name}
                width="128"
                height="128"
            />
            <span>{matrix.name}</span>
        </MenuItem>
    {/each}
</Menu>

// pages/matrices/index.jsx
import { ModalMenu } from "../../components/Modal";
import { MATRICES } from "../../data/en-US/matrices/matrixList";
import { setPageTitle } from "../../components/Layout";
import Head from 'next/head';

function Matrices() {
    return (
        <>
            <Head>
                <title>{setPageTitle('Matrices')}</title>
                <meta name="description" content="Information about all the Matrix set effects in Tower of Fantasy Global and Chinese versions." />
            </Head>

            <img className="bg-img" src={`/static/images/art/${MATRICES[0].imgSrc}`} alt={MATRICES[0].name + " Artwork"} />
            <header>
                <h1>Matrices</h1>
                <p>
                    Matrices (aka Chips) are weapon attachments that provide stat boosts and special effects.<br/>
                    By default the set effect only applies when using the weapon that the matrices are attached to, unless otherwise specified.<br/>
                    There are 4 slots on each weapon; Emotion, Mind, Belief, and Memory. Each of these slots gives slightly different passive stats.<br/>
                    Matrices can be strengthened similar to weapons, with each star unlocking higher values for the set effect.
                </p>
            </header>
            
            <section>
                <h2><span style={{color: "var(--color-tier-s)"}}>SSR</span> Matrices</h2>
                <ModalMenu list={MATRICES} filter="rarity" target="SSR" />
            </section>

            <section>
                <h2><span style={{color: "var(--color-tier-a)"}}>SR</span> Matrices</h2>
                <ModalMenu list={MATRICES} filter="rarity" target="SR" />
            </section>

            <section>
                <h2><span style={{color: "var(--color-tier-b)"}}>R</span> Matrices</h2>
                <ModalMenu list={MATRICES} filter="rarity" target="R" />
            </section>

        </>
    );
}

export default Matrices;
