// src/routes/[[mode]]/cosmetics/mia/+page.svelte
<script>
    import SvelteMarkdown from "svelte-markdown";
    import outfits from "$lib/data/cosmetics/mia.json";
    import Ad from "$lib/components/Ad/Ad.svelte";
    import Youtube from "$lib/components/Youtube.svelte";

    let previewVidSrc = "https://www.youtube.com/embed/R4fCNLUbeQk";
    
    function updateUrl(src) {
        previewVidSrc = src;
    }
</script>

<svelte:head>
    <title>Mi-a Outfits | Tower of Fantasy Index</title>
    <meta name="description" content="List of cosmetic Mi-a outfits and how to get them.">
    <meta property="og:title" content="Mi-a Outfits" />
    <meta
        property="og:description"
        content="List of cosmetic Mi-a outfits and how to get them."
    />
    <meta
        property="og:image"
        content={`/images/Icon/item/${outfits[0].imgSrc}.webp`}
    />
    <meta name="theme-color" content="#377dcb" />
</svelte:head>

<h1>Mi-a Outfits</h1>

<Youtube id="preview" source={previewVidSrc} caption="Preview of most Mi-a outfits from version 2.4." />

<Ad unit="Banner1" />

<div class="table-wrapper">
    <table class="bg-alternate">
        <thead>
            <th>Item</th>
            <th>Source</th>
            <th>Video</th>
        </thead>
        <tbody>
            {#each outfits as outfit}
                <tr>
                    <td>
                        <div class="img-and-name">
                            <img
                                src={`/images/Icon/item/${outfit.imgSrc}.webp`}
                                alt={outfit.name}
                                width="128"
                                height="128"
                                loading="lazy"
                            />
                            <h2>{outfit.name}</h2>
                        </div>
                    </td>
                    <td>
                        <SvelteMarkdown source={outfit.source} />
                    </td>
                    <td>
                        {#if outfit.videoSrc}
                            <a href="#preview" on:click={() => updateUrl(outfit.videoSrc)}>View</a>
                        {/if}
                    </td>
                </tr>
            {/each}
        </tbody>
    </table>
</div>

// pages/cosmetics/mia/index.jsx
import { ModalMenu } from "../../../components/Modal";
import { MIA_OUTFITS } from "../../../data/en-US/cosmetics/cosmetics";
import { setPageTitle } from "../../../components/Layout";
import Head from 'next/head';
import Ads from "../../../components/Ads";

function MiaOutfits() {
    return (
        <>
            <Head>
                <title>{setPageTitle('Mi-a Outfits')}</title>
                <meta name="description" content="List of all Mi-a outfits and how to obtain them in Tower of Fantasy Global and Chinese versions." />
            </Head>

            <img className="bg-img" src="/static/images/bg-1.webp" alt="Background Image" />
            <header>
                <h1>Mi-a Outfits</h1>
                <p>
                    Mi-a can join you as a cosmetic companion NPC, and her outfit can be customized to the options below.
                </p>
            </header>

            <Ads unit="lb1" />

            <section>
                <h2>Mi-a Outfit List</h2>
                <ModalMenu list={MIA_OUTFITS} />
            </section>

            <Ads unit="lb3" />
            <Ads unit="mpu1" />
        </>
    );
}

export default MiaOutfits;
