// pages/cosmetics/chat-bubbles/index.jsx
import { ModalMenu } from "../../../components/Modal";
import { CHAT_BUBBLES } from "../../../data/en-US/cosmetics/cosmetics";
import { setPageTitle } from "../../../components/Layout";
import Head from 'next/head';
import Ads from "../../../components/Ads";

function ChatBubbles() {
    return (
        <>
            <Head>
                <title>{setPageTitle('Chat Bubbles')}</title>
                <meta name="description" content="List of all chat bubbles and how to obtain them in Tower of Fantasy Global and Chinese versions." />
            </Head>

            <img className="bg-img" src="/static/images/bg-1.webp" alt="Background Image" />
            <header>
                <h1>Chat Bubbles</h1>
                <p>
                    How to obtain chat bubbles that customize your text border in chat. Many of them are acquired through paid gachapon events or Collector's/Advanced passes.
                </p>
            </header>

            <Ads unit="lb1" />

            <section>
                <h2>Chat Bubble List</h2>
                <ModalMenu list={CHAT_BUBBLES} />
            </section>

            <Ads unit="lb3" />
            <Ads unit="mpu1" />
        </>
    );
}

export default ChatBubbles;

// src/routes/cosmetics/chat-bubbles/+page.svelte
<script>
    import SvelteMarkdown from "svelte-markdown";
    import chatBubbles from "$lib/data/cosmetics/chatBubbles.json";
    import Ad from "$lib/components/Ad.svelte";

    // Before stride gum
    // {
    //     "name": "Enchanting Ice and Snow",
    //     "imgSrc": "",
    //     "source": "From events."
    // },
</script>

<svelte:head>
    <title>Chat Bubbles | Tower of Fantasy Index</title>
    <meta name="description" content="List of cosmetic chat bubbles and how to get them.">
    <meta property="og:title" content="Chat Bubbles" />
    <meta
        property="og:description"
        content="List of cosmetic chat bubbles and how to get them."
    />
    <meta
        property="og:image"
        content={`/images/Icon/chat/qipao/${chatBubbles[0].imgSrc}.webp`}
    />
    <meta name="theme-color" content="#377dcb" />
</svelte:head>

<h1>Chat Bubbles</h1>

<Ad unit="lb1" />
<Ad unit="mobile_mpu1" />

<div class="table-wrapper">
    <table class="bg-alternate">
        <thead>
            <th>Item</th>
            <th>Source</th>
        </thead>
        <tbody>
            {#each chatBubbles as bubble}
                <tr>
                    <td>
                        <div class="img-and-name">
                            <img
                                src={`/images/Icon/chat/qipao/${bubble.imgSrc}.webp`}
                                alt={bubble.name}
                                width="198"
                                height="112"
                                loading="lazy"
                            />
                            <h2>{bubble.name}</h2>
                        </div>
                    </td>
                    <td>
                        <SvelteMarkdown source={bubble.source} />
                    </td>
                </tr>
            {/each}
        </tbody>
    </table>
</div>

<style>
    img {
        width: auto;
        height: auto;
    }
</style>
