// src/routes/cosmetics/+page.svelte
<script>
    import Menu from "$lib/components/Menu.svelte";
    import MenuItem from "$lib/components/MenuItem.svelte";
    import Ad from "$lib/components/Ad.svelte";

    const links = [
        {
            name: "Outfits",
            href: "/cosmetics/outfits",
            imgSrc: "UI/shizhuang/Fashion_icon/item_fashion_icon/fashion_f19",
        },
        {
            name: "Accessories",
            href: "/cosmetics/accessories",
            imgSrc: "UI/shizhuang/Fashion_icon/fashion_icon_shipin_045",
        },
        {
            name: "Headwear",
            href: "/cosmetics/headwear",
            imgSrc: "UI/shizhuang/Fashion_icon/fashion_icon_shipin_087",
        },
        {
            name: "Refit",
            href: "/cosmetics/refit",
            imgSrc: "UI/shizhuang/Fashion_icon/Overlooker",
        },
        {
            name: "Mi-a Outfits",
            href: "/cosmetics/mia",
            imgSrc: "Icon/item/256mia011",
        },
        {
            name: "Avatars",
            href: "/cosmetics/avatars",
            imgSrc: "Icon/Avatar/Avatar33",
        },
        {
            name: "Avatar Frames",
            href: "/cosmetics/avatar-frames",
            imgSrc: "Icon/AvatarFrame/AvatarFrame_47",
        },
        {
            name: "Chat Bubbles",
            href: "/cosmetics/chat-bubbles",
            imgSrc: "Icon/chat/qipao/icon_qipao_48",
        },
    ];
</script>

<svelte:head>
    <title>Cosmetics | Tower of Fantasy Index</title>
    <meta
        name="description"
        content="Cosmetic items allow you customize the appearance of your character and other social features. Many cosmetics require you to spend real money, but some can be acquired for free."
    />
    <meta property="og:title" content="Cosmetics" />
    <meta
        property="og:description"
        content="Cosmetic items allow you customize the appearance of your character and other social features. Many cosmetics require you to spend real money, but some can be acquired for free. Cosmetic gachapon items may have reruns."
    />
    <meta
        property="og:image"
        content="/images/UI/shizhuang/Fashion_icon/item_fashion_icon/fashion_f19.webp"
    />
    <meta name="theme-color" content="#377dcb" />
</svelte:head>

<h1>Cosmetics</h1>
<p>
    Cosmetic items allow you customize the appearance of your character and
    other social features. Many cosmetics require you to spend real money, but
    some can be acquired for free. Cosmetic gachapon items may have reruns.
</p>

<Ad unit="lb1" />
<Ad unit="mobile_mpu1" />

<Menu>
    {#each links as link}
        <MenuItem href={link.href}>
            <img
                src={`/images/${link.imgSrc}.webp`}
                alt={link.name}
                width="128"
                height="128"
            />
            <span class="menu-item-name">{link.name}</span>
        </MenuItem>
    {/each}
</Menu>

// pages/cosmetics/index.jsx
import { ModalMenu } from "../../components/Modal";
import { setPageTitle } from "../../components/Layout";
import Head from 'next/head';
import Ads from "../../components/Ads";

export const COSMETICS = [
    {
        name: "Outfits",
        uri: "outfits",
        imgSrc: "outfits/F_academyera.webp",
    },
    {
        name: "Accessories",
        uri: "accessories",
        imgSrc: "accessories/disguise-sunglasses.webp",
    },
    {
        name: "Headwear",
        uri: "headwear",
        imgSrc: "headwear/illusory-crown.webp",
    },
    {
        name: "Mi-a Outfits",
        uri: "mia",
        imgSrc: "mia/koimia.webp",
    },
    {
        name: "Avatars",
        uri: "avatars",
        imgSrc: "avatars/travel-shirli.webp",
    },
    {
        name: "Avatar Frames",
        uri: "avatar-frames",
        imgSrc: "avatar-frames/gaze-mirroria.webp",
    },
    {
        name: "Chat Bubbles",
        uri: "chat-bubbles",
        imgSrc: "chat-bubbles/glimpse.webp",
    },
]

function Cosmetics() {
    return (
        <>
            <Head>
                <title>{setPageTitle('Cosmetics')}</title>
                <meta name="description" content="List of all cosmetic items in Tower of Fantasy Global and Chinese versions. How to obtain all outfits, accessories, headwear, Mi-a outfits, avatars, avatar frames, and chat bubbles." />
            </Head>

            <img className="bg-img" src="/static/images/bg-1.webp" alt="Background Image" />
            <header>
                <h1>Cosmetics</h1>
                <p>
                    List of all cosmetic outfits, accessories, headwear, Mi-a outfits, avatars, avatar frames, chat bubbles and how to obtain them.
                </p>
            </header>

            <Ads unit="lb1" />

            <section>
                <h2>Cosmetic Items</h2>
                <ModalMenu list={COSMETICS} />
            </section>

            <Ads unit="lb3" />
            <Ads unit="mpu1" />
        </>
    );
}

export default Cosmetics;
