// pages/changelog.jsx
import { CHANGELOG } from "../data/en-US/changelog";
import Head from "next/head";

const changelogContent = CHANGELOG.map(update => <tr key={update.date}><th>{update.date}</th><td>{update.text}</td></tr>);

export default function Changelog() {
    return (
        <>
            <Head>
                <title>{setPageTitle('Changelog')}</title>
                <meta name="description" content="List of updates and changes to the Tower of Fantasy Index website." />
            </Head>
            <h1>Changelog</h1>
            <table className="changelog w-75ch">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Changes</th>
                    </tr>
                </thead>
                <tbody>{changelogContent}</tbody>
            </table>
        </>
    )
}

// src/routes/changelog/+page.svelte
<script>
    import changelog from "$lib/data/changelog.json";
</script>

<svelte:head>
    <title>Changelog | Tower of Fantasy Index</title>
    <meta name="description" content="A list of all updates and changes to the Tower of Fantasy index.">
    <meta property="og:title" content="Changelog" />
    <meta
        property="og:description"
        content="A list of all updates and changes to the Tower of Fantasy index."
    />
    <meta
        property="og:image"
        content="/images/41.gif"
    />
    <meta name="theme-color" content="#377dcb" />
</svelte:head>

<h1>Changelog</h1>
<ul>
    {#each changelog as update}
        <li>
            <h2>{update.date}</h2>
            <p>{update.text}</p>
        </li>
    {/each}
</ul>

<style lang="scss">
    ul {
        list-style: none;
        margin: 0;
        padding: 0;
    }

    h2 {
        font-size: var(--step-2);
        margin-top: var(--space-s);
        color: var(--accent);
    }
</style>
