// pages/matrices/index.jsx
import { ModalMenu } from "../../components/Modal/Modal";
import { MATRICES } from "../../data/en-US/matrices/matrixList";
import { removeSpace } from "../../utils/stringHelper";
import Layout, { setPageTitle } from "../../components/Layout";
import Head from 'next/head';

function Matrices() {
    return (
        <Layout>
            <Head>
                <title>{setPageTitle('Matrices')}</title>
                <meta name="description" content="Information about all the Matrix set effects in Tower of Fantasy Global and Chinese versions." />
            </Head>

            <img className="bg-img" src={`/images/art/${removeSpace(MATRICES[0].name)}.png`} alt={MATRICES[0].name + " Artwork"} />
            <header>
                <h1>Matrices</h1>
                <p>
                    Matrices (aka Chips) are weapon attachments that provide stat boosts and special effects.<br/>
                    There are 4 slots on each weapon; Emotion, Mind, Belief, and Memory. Each of these slots gives slightly different passive stats.<br/>
                    Matrices can be strengthened similar to weapons, with each star unlocking higher values for the set effect.
                </p>
            </header>
            
            <section>
                <h2><span style={{color: "var(--color-tier-s)"}}>SSR</span> Matrices</h2>
                <ModalMenu list={MATRICES} filter="rarity" target="SSR" />
            </section>

            <section>
                <h2><span style={{color: "var(--color-tier-a)"}}>SR</span> Matrices</h2>
                <ModalMenu list={MATRICES} filter="rarity" target="SR" />
            </section>

            <section>
                <h2><span style={{color: "var(--color-tier-b)"}}>R</span> Matrices</h2>
                <ModalMenu list={MATRICES} filter="rarity" target="R" />
            </section>

        </Layout>
    );
}

export default Matrices;

// src/routes/[[mode]]/matrices/+page.svelte
<script>
    import { searchTerm } from "$lib/stores";
    import Meta from "$components/Meta.svelte";
    import EntryItem from "$components/EntryItem.svelte";

    export let data;
    $: entries = data.matrices.filter((entry) =>
        entry.name.toLowerCase().includes($searchTerm.toLowerCase()),
    );
</script>

<Meta
    title="Matrices | Tower of Fantasy Index"
    description="Matrices (aka Chips) are items that can be attached to one of four slots on a weapon (Emotion, Mind, Belief, and Memory) to provide stat boosts and special effects."
    image={entries[0].assets.iconLarge}
/>

<h1>Matrices</h1>
<p>
    Matrices (aka Chips) are items that can be attached to one of four slots on
    a weapon (Emotion, Mind, Belief, and Memory) to provide stat boosts and
    special effects.
</p>

<ul class="entry-list">
    {#each entries as entry (entry.id)}
        <EntryItem
            {entry}
            slot="search-results"
            isNew={entry.id === data.matrices[0].id}
        />
    {/each}
</ul>
