// pages/mounts/index.jsx
import { ModalMenu } from "../../components/Modal/Modal";
import { MOUNTS } from "../../data/en-US/mounts/mountList";
import Layout, { setPageTitle } from "../../components/Layout";
import Head from 'next/head';

function Mounts() {
    return (
        <Layout>
            <Head>
                <title>{setPageTitle('Mounts')}</title>
                <meta name="description" content="How to obtain all the mounts in Tower of Fantasy Global and Chinese versions." />
            </Head>

            <img className="bg-img" src="/images/bg-2.png" alt="Background Image" />
            <header>
                <h1>Mounts</h1>
                <p>
                    All mounts move at the same speed. Multiple mounts can unlock achievements, and maintaining mounts will reward you with dark crystals. Some mounts have different colors available at certain levels.
                </p>
            </header>
            
            <section>
                <h2>Mount List</h2>
                <ModalMenu list={MOUNTS} />
            </section>
        </Layout>
    );
}

export default Mounts;

// src/routes/mounts/+page.svelte
<script>
    import Menu from "$lib/components/Menu.svelte";
    import MenuItem from "$lib/components/MenuItem.svelte";

    export let data;
    const mounts = data.items;
</script>

<h1>Mounts</h1>
<p>
    All mounts move at the same speed. Multiple mounts can unlock achievements,
    and maintaining mounts will reward you with dark crystals. Some mounts have
    different colors available at certain levels.
</p>

<Menu>
    {#each mounts as mount}
        <MenuItem href={mount.path} chinaOnly={mount.chinaOnly}>
            <img
                src={`/images/UI/Mount/${mount.imgSrc}.png`}
                alt={mount.name}
                width="308"
                height="206"
            />
            <span>{mount.name}</span>
        </MenuItem>
    {/each}
</Menu>

<style lang="scss">
    img {
        // margin-top: 1rem;
        width: 140%;
        height: auto;
    }
</style>
