// src/routes/[[mode]]/relics/+page.svelte
<script>
    import { searchTerm } from "$lib/stores";
    import Meta from "$components/Meta.svelte";
    import EntryItem from "$components/EntryItem/EntryItem.svelte";

    export let data;

    $: entries = data.relics.filter(
        (entry) =>
            entry.name?.toLowerCase().includes($searchTerm.toLowerCase())
    );
</script>

<Meta
    title="Relics | Tower of Fantasy Index"
    description="Relics (aka Gadgets) are tools that aid the player in exploration or combat."
    image={entries[0].icon}
/>

<h1>Relics</h1>
<p>
    Relics (aka Gadgets) are tools that aid the player in exploration or combat.
</p>

<ul class="entry-list">
    {#each entries as entry (entry.id)}
        <EntryItem
            {entry}
            slot="search-results"
            isNew={entry.id === data.relics[0].id}
        />
    {/each}
</ul>

// pages/relics/index.jsx
import { ModalMenu } from "../../components/Modal";
import { RELICS } from "../../data/en-US/relics/relicList";
import { setPageTitle } from "../../components/Layout";
import Head from 'next/head';

function Relics() {
    return (
        <>
            <Head>
                <title>{setPageTitle('Relics')}</title>
                <meta name="description" content="Information about all the Relics in Tower of Fantasy Global and Chinese versions." />
            </Head>

            <img className="bg-img" src={`/images/relics/alternatedestiny.png`} alt="Alternate Destiny" />
            <header>
                <h1>Relics</h1>
                <p>
                    Relics (aka Gadgets) are tools that aid the player in exploration or combat.
                </p>
            </header>
            
            <section>
                <h2><span style={{color: "var(--color-tier-s)"}}>SSR</span> Relics</h2>
                <ModalMenu list={RELICS} filter="rarity" target="SSR" />
            </section>

            <section>
                <h2><span style={{color: "var(--color-tier-a)"}}>SR</span> Relics</h2>
                <ModalMenu list={RELICS} filter="rarity" target="SR" />
            </section>
        </>
    );
}

export default Relics;
