// src/routes/[[mode]]/food/+page.svelte
<script>
    import Meta from "$components/Meta.svelte";
    import SvelteMarkdown from "svelte-markdown";
    import ItemIcon from "$lib/components/ItemIcon.svelte";
    import SearchBar from "$components/Filters/SearchBar.svelte";
    import TypeFilters from "$components/Filters/TypeFilters.svelte";
    import { queryParameters } from "sveltekit-search-params";
    import TypeSelector from "$lib/components/Filters/TypeSelector.svelte";

    export let data;
    const { foods, items, allEffects } = data;
    const searchParams = queryParameters();

    $: entries =
        foods
            .filter((entry) => {
                const { q, rarity, effects, type } = $searchParams;
                const searchMatch = q
                    ? entry.name?.toLowerCase().includes(q.toLowerCase())
                    : true;

                const rarityMatch = rarity
                    ? rarity.split(" ").includes(entry.rarity.toString())
                    : true;

                const effectsMatch = effects
                    ? effects
                          .split(" ")
                          .some((effect) => entry.categories.includes(effect))
                    : true;

                const typeMatch =
                    type && type !== "all" ? entry.buff === type : true;

                return searchMatch && rarityMatch && effectsMatch && typeMatch;
            })
            .toSorted((a, b) => a.rarity - b.rarity)
            .filter((entry) => entry.categories.length > 1);

    function getIngredientInfo(id) {
        return items.find((item) => item.id.toLowerCase() === id.toLowerCase());
    }
</script>

<Meta
    title="Food | Tower of Fantasy Index"
    description="Food can provide buffs and recover HP, satiety, and stamina. Satiety level determines how much HP you will passively recover while out of combat."
/>

<h1>Food</h1>
<p>
    Food can provide buffs and recover HP, satiety, and stamina. Satiety level
    determines how much HP you will passively recover while out of combat.
</p>
<p>
    To permanently unlock a recipe, you will have to successfully cook the dish
    once. Add extra amounts of the correct ingredients to boost your success
    rate!
</p>

<div class="filters-row">
    <SearchBar />
    <TypeFilters type="rarity" />
    <TypeFilters type="effects" filters={allEffects} />
    <TypeSelector originalData={foods} key="buff" />
</div>

<table class="food-table bg-alternate">
    <thead>
        <tr>
            <th>Dish</th>
            <th>Recipe</th>
        </tr>
    </thead>
    <tbody>
        {#each entries as food}
            <tr>
                <td>
                    <div class="flex g-100" style="align-items: center">
                        <div class="item-wrapper">
                            <ItemIcon item={food} />
                            <!-- {food.categories} -->
                        </div>
                        <div>
                            <small>{food.buff}</small>
                            <h2>{food.name}</h2>
                            <SvelteMarkdown source={food.effect ?? ""} />
                            <p class="desc">{food.description}</p>
                            {food.categories}
                        </div>
                    </div>
                </td>
                <td>
                    {#if food.ingredients}
                        <ul role="list">
                            {#each food.ingredients as ingredient}
                                <li
                                    class="flex g-100"
                                    style="align-items: center"
                                >
                                    <div class="item-wrapper">
                                        <ItemIcon
                                            item={{
                                                ...getIngredientInfo(
                                                    ingredient.matID,
                                                ),
                                                amount: ingredient.min,
                                            }}
                                            imgSize="48"
                                            wrapperSize="48px"
                                        />
                                    </div>
                                    {getIngredientInfo(ingredient.matID).name}
                                </li>
                            {/each}
                        </ul>
                    {/if}
                </td>
            </tr>
        {/each}
    </tbody>
</table>

<style lang="scss">
    table {
        margin: 1rem 0;
    }

    h2 {
        font-size: var(--step-1);
        font-weight: 500;
        margin: 0;
        line-height: normal;
    }

    ul {
        margin: 0;
        padding: 0;
        list-style-type: none;
        gap: unset;
    }

    .item-wrapper {
        width: fit-content;
        margin-bottom: 0.5rem;
    }

    .desc {
        font-size: var(--step--2);
        color: var(--text2);
        line-height: 1.4;
        display: none;
    }
</style>

// pages/food/index.jsx
// import ReactMarkdown from "react-markdown";
import dishes from "../../data/en-US/food/dishes";
import { setPageTitle } from "../../components/Layout";
import Head from 'next/head';
import ReactMarkdown from "react-markdown";

function Food() {
    const getRecipe = (dish) => {
        return dish.ingredients.map(ingredient =>
            <li key={ingredient.item.name} className="ingredient">
                <div className={`item-frame rarity-${ingredient.item.rarity}`}>
                    <img src={`/images/food/ingredients/${ingredient.item.imgSrc}`} alt={ingredient.item.name} />
                    <h3>{ingredient.amount}</h3>
                </div>
                {ingredient.item.name}
            </li>
        );
    }

    const foodList = dishes.map(dish => {
        const recipe = getRecipe(dish);
        return (
            <tr key={dish.name}>
                <th className="col-dish">
                    <div className={`item-frame rarity-${dish.rarity}`}>
                        {dish.chinaOnly && <abbr title="China Exclusive" />}
                        <img src={`/images/food/dishes/${dish.imgSrc}`} alt={dish.name} />
                    </div>
                    <span>{dish.name}</span>
                </th>
                <td className="col-effect"><ReactMarkdown>{dish.effect}</ReactMarkdown></td>
                <td className="col-recipe"><ul className="ingredient-list">{recipe}</ul></td>
            </tr>
        )
    });

    return (
        <>
            <Head>
                <title>{setPageTitle('Food')}</title>
                <meta name="description" content="Recipes for craftable food in Tower of Fantasy Global and Chinese versions." />
            </Head>
            
            <img className="bg-img" src="/images/food/huodong_meishi_guo.png" alt="Dancing Air Fryer" />
            <header>
                <h1>Food</h1>
                <p>
                    Food can provide buffs and recover HP, satiety (hunger), and stamina.<br />
                    Satiety level determines how much HP you will passively recover while out of combat.<br />
                    When learning a new recipe, adding extra of the required ingredients will boost the chance of permanently unlocking the recipe.
                </p>
            </header>
            <section>
                <menu className="filters" style={{ display: 'none' }}>
                    <li>
                        <h4>Rarity</h4>
                        <div className="flex">
                            <div className="rarity-1"></div>
                            <div className="rarity-2"></div>
                            <div className="rarity-3"></div>
                            <div className="rarity-4"></div>
                            <div className="rarity-5"></div>
                        </div>
                    </li>
                    <li>
                        <h4>Offensive</h4>
                        <div className="flex">
                            <input type="checkbox" id="atk_flame" name="atk_flame" />
                            <label htmlFor="atk_flame">
                                <img src="/images/buff/ATK_flame.png" alt="Flame Attack" />
                            </label>
                            <input type="checkbox" id="atk_ice" name="atk_ice" />
                            <label htmlFor="atk_ice">
                                <img src="/images/buff/ATK_ice.png" alt="Ice Attack" />
                            </label>
                            <input type="checkbox" id="atk_volt" name="atk_volt" />
                            <label htmlFor="atk_volt">
                                <img src="/images/buff/ATK_volt.png" alt="Volt Attack" />
                            </label>
                            <input type="checkbox" id="atk_physical" name="atk_physical" />
                            <label htmlFor="atk_physical">
                                <img src="/images/buff/ATK_physical.png" alt="Physical Attack" />
                            </label>
                        </div>
                    </li>
                    <li>
                        <h4>Defensive</h4>
                        <div className="flex">
                            <img src="/images/buff/DEF_flame.png" alt="Flame Defense" />
                            <img src="/images/buff/DEF_ice.png" alt="Ice Defense" />
                            <img src="/images/buff/DEF_volt.png" alt="Volt Defense" />
                            <img src="/images/buff/DEF_physical.png" alt="Physical Defense" />
                        </div>
                    </li>
                    <li>
                        <h4>Recovery</h4>
                        <div className="flex">
                            <img src="/images/buff/HP.png" alt="HP Recovery" />
                            <img src="/images/buff/stamina.png" alt="Stamina Recovery" />
                        </div>
                    </li>



                </menu>
                <table className="food-list">
                    <thead>
                        <tr>
                            <th><h5>Dish</h5></th>
                            <th><h5>Effect</h5></th>
                            <th><h5>Recipe</h5></th>
                        </tr>
                    </thead>
                    <tbody>
                        {foodList}
                    </tbody>
                </table>
            </section>
        </>
    );
}

export default Food;
