// src/routes/food/+page.svelte
<script>
    import SvelteMarkdown from "svelte-markdown";
    import ingredientsData from "$lib/data/food/ingredients.json";
    import dishesData from "$lib/data/food/dishes.json";
    import SectionNavigation from "$lib/components/SectionNavigation.svelte";
    import { onMount } from "svelte";
    import AnchorJS from "anchor-js";
    import Item from "$lib/components/Item.svelte";
    import EffectIcon from "$lib/components/food/EffectIcon.svelte";
    import FoodFilters from "../../lib/components/food/FoodFilters.svelte";
    import Ad from "$lib/components/Ad.svelte";

    onMount(() => {
        const anchors = new AnchorJS();
        anchors.add("h3");
    });

    function getIngredientData(input) {
        return ingredients.find((i) => i.name === input);
    };

    let dishes = dishesData;
    let ingredients = ingredientsData;
    let filters = {};

    // Filters are AND, i.e. volt ATK && rarity 4
    // They are not OR, i.e. volt ATK || rarity 4
    $: if (filters.rarityFilters && filters.rarityFilters.length > 0) {
        dishes = dishesData.filter((dish) =>
            filters.rarityFilters.includes(dish.rarity)
        );
    } else {
        dishes = dishesData;
    }

    $: if (filters.buffFilters && filters.buffFilters.length > 0) {
        dishes = dishes.filter((dish) =>
            dish.icons && dish.icons.some(t => filters.buffFilters.includes(t))
        );
    } 

    $: if (filters.recoveryFilters && filters.recoveryFilters.length > 0) {
        dishes = dishes.filter((dish) =>
            dish.icons && dish.icons.some(t => filters.recoveryFilters.includes(t))
        );
    }
</script>

<svelte:head>
    <title>Food | Tower of Fantasy Index</title>
    <meta name="description" content="Food can provide buffs and recover HP, satiety, and stamina. Satiety level determines how much HP you will passively recover while out of combat.">
    <meta property="og:title" content="Food" />
    <meta
        property="og:description"
        content="Food can provide buffs and recover HP, satiety, and stamina. Satiety level determines how much HP you will passively recover while out of combat."
    />
    <meta
        property="og:image"
        content="/images/Icon/caiyao/Item_Vera_Cooking29.png"
    />
    <meta name="theme-color" content="#377dcb" />
</svelte:head>

<SectionNavigation links={["dishes", "ingredients"]} />
<h1>Food</h1>

<p>
    Food can provide buffs and recover HP, satiety, and stamina. Satiety level
    determines how much HP you will passively recover while out of combat.
</p>
<p>
    To permanently unlock a recipe, you will have to successfully cook the dish
    once. Add extra amounts of the correct ingredients to boost your success
    rate!
</p>

<FoodFilters bind:filters />

<Ad unit="lb1" />
<Ad unit="mobile_mpu1" />

<h2 id="dishes">Dishes</h2>
<div class="table-wrapper">
    <table class="dishes-table bg-alternate">
        <thead>
            <th>Item</th>
            <th>Effect</th>
            <th>Recipe</th>
        </thead>
        <tbody>
            {#each dishes as dish}
                <tr>
                    <td>
                        <div class="img-and-name">
                            <Item rarity={dish.rarity}>
                                <img
                                    src={`/images/Icon/caiyao/${dish.imgSrc}.png`}
                                    alt={dish.name}
                                    width="96"
                                    height="96"
                                    loading="lazy"
                                />
                                {#if dish.icons}
                                    {#each dish.icons as effect}
                                        <EffectIcon {effect} absolute />
                                    {/each}
                                {/if}
                            </Item>
                            <h3>{dish.name}</h3>
                        </div>
                    </td>
                    <td class="dish-effects">
                        <SvelteMarkdown source={dish.effect} />
                    </td>
                    <td>
                        <ul class="recipe">
                            {#each dish.ingredients as ingredient}
                                <li>
                                    <Item
                                        rarity={getIngredientData(
                                            ingredient.item
                                        ).rarity}
                                        amount={ingredient.amount}
                                    >
                                        <img
                                            src={`/images/Icon/shicai/${
                                                getIngredientData(
                                                    ingredient.item
                                                ).imgSrc
                                            }.png`}
                                            alt={ingredient.item}
                                            width="48"
                                            height="48"
                                            loading="lazy"
                                        />
                                    </Item>
                                    <a
                                        href={`#${ingredient.item
                                            .toLowerCase()
                                            .replace(/\s+/g, "-")}`}
                                    >
                                        {ingredient.item}
                                    </a>
                                </li>
                            {/each}
                        </ul>
                    </td>
                </tr>
            {/each}
        </tbody>
    </table>
</div>

<Ad unit="lb3" />
<Ad unit="mobile_mpu2" />

<h2 id="ingredients">Ingredients</h2>
<div class="table-wrapper">
    <table class="bg-alternate">
        <thead>
            <th>Item</th>
            <th>Source</th>
        </thead>
        <tbody>
            {#each ingredients as ingredient}
                <tr>
                    <td class="img-and-name">
                        <img
                            src={`/images/Icon/shicai/${ingredient.imgSrc}.png`}
                            alt={ingredient.name}
                            width="64"
                            height="64"
                            loading="lazy"
                        />
                        <h3>{ingredient.name}</h3>
                    </td>
                    <td>
                        <SvelteMarkdown source={ingredient.source} />
                    </td>
                </tr>
            {/each}
        </tbody>
    </table>
</div>

<style lang="scss">
    .img-and-name {
        row-gap: 0.5rem;
    }

    .dishes-table {
        table-layout: fixed;
    }

    ul.recipe {
        margin: 0;
        padding: 0;
        list-style: none;

        li {
            display: flex;
            align-items: center;
            gap: 0.5rem;

            a {
                font-size: var(--step--1);
                line-height: 1.2;
            }
        }
    }
</style>

// pages/food/index.jsx
// import ReactMarkdown from "react-markdown";
import dishes from "../../data/en-US/food/dishes";
import { setPageTitle } from "../../components/Layout";
import Head from 'next/head';
import ReactMarkdown from "react-markdown";
import Ads from "../../components/Ads";

function Food() {
    const getRecipe = (dish) => {
        return dish.ingredients.map(ingredient =>
            <li key={ingredient.item.name} className="ingredient">
                <div className={`item-frame rarity-${ingredient.item.rarity}`}>
                    <img src={`/static/images/food/ingredients/${ingredient.item.imgSrc}`} alt={ingredient.item.name} />
                    <h3>{ingredient.amount}</h3>
                </div>
                {ingredient.item.name}
            </li>
        );
    }

    const foodList = dishes.map(dish => {
        const recipe = getRecipe(dish);
        return (
            <tr key={dish.name}>
                <th className="col-dish">
                    <div className={`item-frame rarity-${dish.rarity}`}>
                        {dish.chinaOnly && <abbr title="China Exclusive" />}
                        <img src={`/static/images/food/dishes/${dish.imgSrc}`} alt={dish.name} />
                    </div>
                    <span>{dish.name}</span>
                </th>
                <td className="col-effect"><ReactMarkdown>{dish.effect}</ReactMarkdown></td>
                <td className="col-recipe"><ul className="ingredient-list">{recipe}</ul></td>
            </tr>
        )
    });

    return (
        <>
            <Head>
                <title>{setPageTitle('Food')}</title>
                <meta name="description" content="Recipes for craftable food in Tower of Fantasy Global and Chinese versions." />
            </Head>
            
            <img className="bg-img" src="/static/images/food/huodong_meishi_guo.webp" alt="Dancing Air Fryer" />
            <header>
                <h1>Food</h1>
                <p>
                    Food can provide buffs and recover HP, satiety (hunger), and stamina.<br />
                    Satiety level determines how much HP you will passively recover while out of combat.<br />
                    When learning a new recipe, adding extra of the required ingredients will boost the chance of permanently unlocking the recipe.
                </p>
            </header>

            <Ads unit="lb1" />

            <section>
                <menu className="filters" style={{ display: 'none' }}>
                    <li>
                        <h4>Rarity</h4>
                        <div className="flex">
                            <div className="rarity-1"></div>
                            <div className="rarity-2"></div>
                            <div className="rarity-3"></div>
                            <div className="rarity-4"></div>
                            <div className="rarity-5"></div>
                        </div>
                    </li>
                    <li>
                        <h4>Offensive</h4>
                        <div className="flex">
                            <input type="checkbox" id="atk_flame" name="atk_flame" />
                            <label htmlFor="atk_flame">
                                <img src="/static/images/buff/ATK_flame.webp" alt="Flame Attack" />
                            </label>
                            <input type="checkbox" id="atk_ice" name="atk_ice" />
                            <label htmlFor="atk_ice">
                                <img src="/static/images/buff/ATK_ice.webp" alt="Ice Attack" />
                            </label>
                            <input type="checkbox" id="atk_volt" name="atk_volt" />
                            <label htmlFor="atk_volt">
                                <img src="/static/images/buff/ATK_volt.webp" alt="Volt Attack" />
                            </label>
                            <input type="checkbox" id="atk_physical" name="atk_physical" />
                            <label htmlFor="atk_physical">
                                <img src="/static/images/buff/ATK_physical.webp" alt="Physical Attack" />
                            </label>
                        </div>
                    </li>
                    <li>
                        <h4>Defensive</h4>
                        <div className="flex">
                            <img src="/static/images/buff/DEF_flame.webp" alt="Flame Defense" />
                            <img src="/static/images/buff/DEF_ice.webp" alt="Ice Defense" />
                            <img src="/static/images/buff/DEF_volt.webp" alt="Volt Defense" />
                            <img src="/static/images/buff/DEF_physical.webp" alt="Physical Defense" />
                        </div>
                    </li>
                    <li>
                        <h4>Recovery</h4>
                        <div className="flex">
                            <img src="/static/images/buff/HP.webp" alt="HP Recovery" />
                            <img src="/static/images/buff/stamina.webp" alt="Stamina Recovery" />
                        </div>
                    </li>



                </menu>

                <table className="food-list">
                    <thead>
                        <tr>
                            <th><h5>Dish</h5></th>
                            <th><h5>Effect</h5></th>
                            <th><h5>Recipe</h5></th>
                        </tr>
                    </thead>
                    <tbody>
                        {foodList}
                    </tbody>
                </table>
            </section>

            <Ads unit="lb3" />
            <Ads unit="mpu1" />
        </>
    );
}

export default Food;
