// src/routes/simulacra.tsx
import { ModalMenu, Modal } from "../components/Modal";
import { SSR_CHARACTERS, SR_CHARACTERS } from "../data/en-US/characterList";

function Simulacra() {
    return (
        <main>
            <header>
                <h1>Simulacra</h1>
                <p>
                    Simulacra (aka Mimics) are the player's representation of the characters found in Tower of Fantasy.<br />

                    They have an associated weapon and an optional passive effect. Their associated matrices must be obtained separately.
                </p>
            </header>
            
            <section>
                <h2><span style={{color: "var(--color-tier-s)"}}>SSR</span> Simulacra</h2>
                <ModalMenu listContent={SSR_CHARACTERS} />
            </section>

            <section>
                <h2><span style={{color: "var(--color-tier-a)"}}>SR</span> Simulacra</h2>
                <ModalMenu listContent={SR_CHARACTERS} />
            </section>

        </main>
    );
}

export default Simulacra;

// src/routes/(db)/simulacra/+page.svelte
<script>
    import { searchTerm } from "$lib/stores";
    import Meta from "../Meta.svelte";
    import EntryItem from "../EntryItem.svelte";

    export let data;
    $: ({ Simulacra } = data);
    $: simulacra = $Simulacra?.data?.simulacra_v2.filter(sim => sim.Name.toLowerCase().includes($searchTerm.toLowerCase()))
</script>

{#if !$Simulacra.fetching}
    <Meta
        title="Simulacra | Tower of Fantasy Index"
        description="Simulacra (aka Mimics) are the player's representation of the characters found in Tower of Fantasy. They have an associated weapon and an optional passive effect. Their associated matrices must be obtained separately."
        image="https://api.toweroffantasy.info{$Simulacra.data.simulacra_v2[0].AssetsA0.Avatar}"
    />
    {#each simulacra as entry (entry.id)}
        <EntryItem {entry} />
    {/each}
{/if}
